### ISSUE TITLE
RandomForestClassifier invalid value

### ISSUE THREAD

**Issue by mesti90** [DamianJM/Depolymerase-Predictor#1]
I tried to run the command line version of depp with the following command:
python3 -m depp_cli -i genome.fna -o results

Unfortunately, the following error occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/node10_R10/vasarhelyib/Phageant/Depolymerase-Predictor/DePP_CLI/depp_cli.py", line 46, in <module>
    main()
  File "/node10_R10/vasarhelyib/Phageant/Depolymerase-Predictor/DePP_CLI/depp_cli.py", line 34, in main
    model = train_model(training_set_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/node10_R10/vasarhelyib/Phageant/Depolymerase-Predictor/DePP_CLI/utils/depolymerase_prediction.py", line 34, in train_model
    model_rf = pipelineDP.fit(X, y)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/pipeline.py", line 420, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1144, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.
```

Thank you for your help

**Comment by mesti90** [comment]
After a short research it turned out that the parameter `max_features='auto'` for RandomForestClassifier has been deprecated since scikit-learn 1.1 (see https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html)
I suggest to change line 28 in `utils/depolymerase_prediction.py` accordingly (e.g. to `max_features='sqrt'`)

**Comment by TimSkvortsov** [comment]
Hi @mesti90, thank you for suggesting the fix, it has been added by @DamianJM on 11 Sep 2023 in https://github.com/DamianJM/Depolymerase-Predictor/commit/aedf68719dab89ca177f4b33edf801964ebfb28e

I am now closing this issue.
